export const projects = [
  {
    id: "1",
    title: "Pointer",
    description: "An engaging web application designed to promote positive behavior in children through a fun and interactive reward system, encouraging discipline and personal growth.",
    techStack:"Nextjs, TypeScript, TailwindCSS, Nextauth, PostgreSQL, Prisma, Superbase, Nodemailer, Gemini, Stripe, Bcript, Vercel.",
    imageDescPairs: [
      { image: "/pointer/pointer_home.png", description: "An engaging web application designed to promote positive behavior in children through a fun and interactive reward system, encouraging discipline and personal growth." },
      { image: "/pointer/pointer_main.png", description: "The app includes several features such as creating routines for children, assigning tasks, creating rewards, challenges, and quizzes, and setting budgets for each kid." },
      { image: "/pointer/pointer_rewards.png", description: "The tools used to create this app are Next.js (React.js, TypeScript), TailwindCSS, Nextauth, PostgreSQL, Prisma, Superbase, Nodemailer, Gemini, Stripe, and it is hosted on Vercel." },
      { image: "/pointer/pointer_signup.png", description: "Users can either create an account or login via Google OAuth. Authentication is handled using Nextauth" },
      { image: "/pointer/pointer_verify.png", description: "Email verification is implemented via Nodemailer to ensure email integrity." },
      { image: "/pointer/pointer_confirm.png", description: "Users are prompted to fill in some data to finish setting up their environment, like their children's details and preferences." },
      { image: "/pointer/pointer_plans_2.png", description: "Users can choose to engage in a free trial or subscribe with monthly or yearly payment plans." },
      { image: "/pointer/pointer_payment.png", description: "Secure payment is implemented using Stripe." },
      { image: "/pointer/pointer_child_profile.png", description: "As you open the child’s profile, you’re greeted with a dashboard that organizes their routines, tasks, rewards, and progress. Each child is given a generated username and password to access their account." },
      { image: "/pointer/pointer_rewards_child.png", description: "A dedicated space for celebrating success, where the child’s rewards and achievements are proudly displayed, motivating them to keep pushing forward." },
      { image: "/pointer/pointer_routines_weekly.png", description: "A glance at the weekly routine reveals an intuitive layout where parents can assign tasks and monitor progress seamlessly." },
      { image: "/pointer/pointer_routine_daily.png", description: "The daily breakdown provides a comprehensive view of what’s been done and what still needs attention, empowering kids to stay on top of their responsibilities." },
      { image: "/pointer/pointer_kids_modal.png", description: "Parents can assign tasks to specific children, or create a global task for all their kids." },
      { image: "/pointer/pointer_challenge_form.png", description: "Creating challenges is easy and fun—parents can craft custom tasks with specific rewards, adding a layer of excitement to their child’s day-to-day activities." },
      { image: "/pointer/pointer_challenge_card.png", description: "Each challenge card displays the challenge’s details—what’s at stake, how it’s earned, and the reward awaiting completion." },
      { image: "/pointer/pointer_quizzes.png", description: "Parents can set up engaging quizzes to test their children’s knowledge and progress, the quizzes are generated via Google's Gemini AI, by prompting it with parent's input and child's age." },
      { image: "/pointer/pointer_quizzes_child.png", description: "Children can engage in the quizzes to earn points, they can filter quizzes by topic, review already answered ones, and can track their progress via the point system" },
      { image: "/pointer/pointer_budget.png", description: "Parents can manage their kids' rewards by using the budget tool, ensuring they allocate rewards wisely while maintaining fun incentives for the kids." },
      { image: "/pointer/pointer_notif.png", description: "Parents stay informed with instant notifications about their child’s progress, upcoming tasks, and completed activities, fostering communication and connection." },
      { image: "/pointer/pointer_settings.png", description: "The settings page, built with flexibility in mind, allows users to tailor the app to their unique needs—everything from notifications to account preferences can be fine-tuned here." },
      { image: "/pointer/pointer_freeTrial.png", description: "New users are invited to try the app’s full potential through a risk-free trial, easing them into the experience without any commitment." },
      { image: "/pointer/pointer_plans.png", description: "A detailed breakdown of the available plans showcases the benefits of each, allowing parents to choose the best fit for their needs." },
      { image: "/pointer/pointer_please_pay.png", description: "When the free trial ends, parents are faced with a blocking modal that prompts them to pay for a subscription in order to continue using the app." },
    ],
    conclusion: "While this project is still a work in progress, it holds immense potential for future enhancements. One exciting feature under consideration is a 'Teacher Mode,' which would empower educators to assign homework and track students' grades and progress. This addition would enable parents to monitor their children's academic journey more closely, fostering a collaborative environment between teachers and families. Furthermore, i envision integrating gamification elements to make learning more engaging, along with personalized learning plans tailored to each child's unique needs and preferences. As i continue to develop this application, i aim to create a comprehensive tool that supports not only children’s behavioral growth but also their academic achievements.",
    detailedDescription: [],
    detailsLink: "/projects/1",
    demoLink: "https://pointer-app.vercel.app",
    githubLink: "https://github.com/ahmedrioueche/pointer",
  },
  {
    id: "2",
    title: "Modbus Gateway Manager",
    techStack:"Electronjs, Javascript, Nodejs, CSS, Sqlite, Bcript, Serialport.",
    description: "A Desktop application based on Electron for the configuration and diagnosis of a Modbus gateway, part of my master's degree graduation project supervised by Cevie Doofas Innovative Solutions company.",
    imageDescPairs: [
      { image: "/gm/gm_login.png", description: "This application is a part of bigger project titled Design and Implementation of a Modbus TCP/RTU Industrial Gateway, finished in june 2024 as a part of my graduation project supervised by Cevie Doofas Innovative Solutions. This gateway is created to facilitate communication between industrial machines that use Modbus protocol variations (TCP, RTU)" },
      { image: "/gm/gateway_1.jpg", description: "I designed and built a fully functional PCB using KiCad and developed the firmware in C and C++ with STM32Cube. Additionally, I created a web server using the Mongoose library, serving the same functionality as this Electron app. This project significantly sharpened my technical skills and guided me through the complete process of building a complex, multi-component project from start to finish." },
      { image: "/gm/gm_general.png", description: "The main feature of this app is configuring the Modbus gateway. by specifying different parameters that are used in the gateway's firmware " },
      { image: "/gm/gm_mode.png", description: "Users should configure the Modbus mode (RTU or TCP) that the gateway should run on, for instance, if it is hooked to a machine operating as Modbus RTU client (master), the gateway should be configured as an RTU server (slave), and vice versa." },
      { image: "/gm/gm_serial.png", description: "Users are able to configue the different serial parameters, such as the baudrate, parity, stop bits, data size, and the slave identifier (server id) of the gateway (If its connected to an RTU master (client))" },
      { image: "/gm/gm_network.png", description: "Users are able to configure the IP of the gateway along with the mask and gateway IP, and specify the remote IP of the TCP server machine. The configuration data is sent via USB utilizing the Serialport library." },
      { image: "/gm/gm_diag_1.png", description: "The other main feature of this app is diagnosing the packets going through the gateway. By having copies of the packets sent to the app via USB, users can diagnos and analize the behavior of the gateway and troubleshoot their system." },
      { image: "/gm/gm_settings.png", description: "The app offer settings to change the username, reset password, or change the language (English, french, and spanish). user's data is stored in a local Sqlite database." },
    ],
    conclusion: ".",
    detailsLink: "/projects/2",
    demoLink: "https://demo.projecttwo.com",
    githubLink: "https://github.com/ahmedrioueche/projecttwo",
  },
  {
    id: "3",
    title: "Project Three",
    description: "A brief description of Project Three.",
    imageDescPairs: [
      { image: "/project1.1.png", description: "The homepage of Project Three, highlighting its unique layout and user-friendly design." },
      { image: "/project1.2.png", description: "An admin dashboard of Project Three, offering a comprehensive view of ongoing activities and user interactions." },
      { image: "/project1.3.png", description: "A detailed settings page in Project Three, allowing users to configure their account preferences and notifications." },
    ],
    detailsLink: "/projects/3",
    demoLink: "https://demo.projectthree.com",
    githubLink: "https://github.com/yourusername/projectthree",
  },
];
