export const projects = [
  {
    id: "1",
    title: "Pointer",
    description: "An engaging web application designed to promote positive behavior in children through a fun and interactive reward system, encouraging discipline and personal growth.",
    imageDescPairs: [
      { image: "/pointer/pointer_home.png", description: "An engaging web application designed to promote positive behavior in children through a fun and interactive reward system, encouraging discipline and personal growth" },
      { image: "/pointer/pointer_main.png", description: "The app includes several features such as creating routines for children, assigning tasks, creating rewards, challenges, and quizzes, and setting budgets for each kid." },
      { image: "/pointer/pointer_rewards.png", description: "The tools used to create this app are Next.js (React.js, TypeScript), TailwindCSS, NextAuth, PostgreSQL, Prisma, Superbase, Nodemailer, Gemini, Stripe, and it is hosted on Vercel." },
      { image: "/pointer/pointer_signup.png", description: "Users can either create an account or login via Google OAuth." },
      { image: "/pointer/pointer_verify.png", description: "Email verification is implemented via Nodemailer to ensure email integrity." },
      { image: "/pointer/pointer_confirm.png", description: "Users are prompted to fill in some data to finish setting up their environment, like their children's details and preferences." },
      { image: "/pointer/pointer_plans_2.png", description: "Users can choose to engage in a free trial or subscribe with monthly or yearly payment plans." },
      { image: "/pointer/pointer_payment.png", description: "Secure payment is implemented using Stripe." },
      { image: "/pointer/pointer_child_profile.png", description: "A detailed profile view of a child, showing their routines, tasks, rewards, and progress." },
      { image: "/pointer/pointer_rewards_child.png", description: "A view dedicated to managing the child's rewards, showing their achievements and rewards earned." },
      { image: "/pointer/pointer_routines_weekly.png", description: "A weekly routine view for the child, allowing parents to assign tasks and track progress over time." },
      { image: "/pointer/pointer_routine_daily.png", description: "A detailed breakdown of daily routines, including completed and pending tasks for the child." },
      { image: "/pointer/pointer_settings.png", description: "A settings page where users can configure their preferences, including notification settings and account management." },
      { image: "/pointer/pointer_kids_modal.png", description: "A modal that allows parents to manage multiple children's profiles and switch between them easily." },
      { image: "/pointer/pointer_challenge_form.png", description: "A form to create custom challenges for children to complete, with the option to assign rewards." },
      { image: "/pointer/pointer_challenge_card.png", description: "A view of a challenge card, summarizing the details of a challenge assigned to a child." },
      { image: "/pointer/pointer_budget.png", description: "A budgeting tool that helps parents manage rewards and monetary incentives for their children." },
      { image: "/pointer/pointer_quizzes.png", description: "A feature allowing parents to create and assign educational quizzes to their children as part of the reward system." },
      { image: "/pointer/pointer_quizzes_child.png", description: "A child-facing view of the quizzes, where they can take educational tests and earn rewards." },
      { image: "/pointer/pointer_notif.png", description: "A notifications system to keep parents informed of their child's progress, task completions, and upcoming tasks." },
      { image: "/pointer/pointer_settings.png", description: "Another view of the settings page, focusing on customization and account preferences." },
      { image: "/pointer/pointer_freeTrial.png", description: "An option for users to try the app for free before committing to a subscription." },
      { image: "/pointer/pointer_plans.png", description: "A detailed comparison of the available plans, including pricing and features of the free trial, monthly, and yearly options." },
      { image: "/pointer/pointer_please_pay.png", description: "A payment prompt encouraging users to subscribe to one of the available plans to continue using premium features." },
    ],
    detailedDescription: [],
    detailsLink: "/projects/1",
    demoLink: "http://pointer-app.vercel.app/",
    githubLink: "https://github.com/ahmeddrioueche/pointer",
  },
  {
    id: "2",
    title: "Project Two",
    description: "A brief description of Project Two.",
    imageDescPairs: [
      { image: "/project1.1.png", description: "The landing page of Project Two, showcasing its modern and sleek interface." },
      { image: "/project1.2.png", description: "An internal dashboard view of Project Two, with detailed analytics and user insights." },
      { image: "/project1.3.png", description: "A close-up of the user profile management system in Project Two, featuring customization options and data tracking." },
    ],
    detailsLink: "/projects/2",
    demoLink: "https://demo.projecttwo.com",
    githubLink: "https://github.com/yourusername/projecttwo",
  },
  {
    id: "3",
    title: "Project Three",
    description: "A brief description of Project Three.",
    imageDescPairs: [
      { image: "/project1.1.png", description: "The homepage of Project Three, highlighting its unique layout and user-friendly design." },
      { image: "/project1.2.png", description: "An admin dashboard of Project Three, offering a comprehensive view of ongoing activities and user interactions." },
      { image: "/project1.3.png", description: "A detailed settings page in Project Three, allowing users to configure their account preferences and notifications." },
    ],
    detailsLink: "/projects/3",
    demoLink: "https://demo.projectthree.com",
    githubLink: "https://github.com/yourusername/projectthree",
  },
];
